[package]
name = "simple-robot"
version = "0.1.0"
authors = ["Esteban <esteban.sotillo@olympe.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
custom_error = "1.8.0"
regex = "1.4.2"